# Generated by Django 4.2.23 on 2025-09-09 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_total_cars'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='damage_reported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='pending_payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='car',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
