# Generated by Django 4.2.23 on 2025-09-16 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_customer_aadhar_number_alter_customer_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(default='default_avatar.png', upload_to='profile_pics/'),
        ),
    ]
