# Generated by Django 4.2.23 on 2025-10-17 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_customer_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='is_returned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
