# Generated by Django 4.2.23 on 2025-10-17 03:40

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_booking_is_returned_booking_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='damage_reported',
            field=models.BooleanField(default=False),
        ),
    ]
