# Generated by Django 4.2.23 on 2025-10-17 05:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_booking_damage_fee_booking_damage_reported'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='pending_payment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
