# Generated by Django 4.2.23 on 2025-10-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_car_with_driver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='driver',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='self_drive',
        ),
        migrations.RemoveField(
            model_name='car',
            name='per_hour_charge',
        ),
        migrations.RemoveField(
            model_name='car',
            name='per_km_charge',
        ),
        migrations.RemoveField(
            model_name='car',
            name='with_driver',
        ),
        migrations.AddField(
            model_name='booking',
            name='drive_type',
            field=models.CharField(choices=[('self_drive', 'Self Drive'), ('with_driver', 'With Driver')], default='self_drive', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='hours_used',
            field=models.IntegerField(default=4),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_hour',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='car',
            name='price_per_km',
            field=models.FloatField(default=0),
        ),
    ]
