# Generated by Django 4.2.23 on 2025-10-24 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_booking_driver_remove_booking_self_drive_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driver',
            name='assigned_car',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years of experience'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_km_reading',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
    ]
