# Generated by Django 4.2.23 on 2025-10-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_remove_driver_assigned_car_driver_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('ON_LEAVE', 'On Leave')], default='AVAILABLE', max_length=20),
        ),
    ]
