# Generated by Django 4.2.23 on 2025-09-04 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Ambassador', 'Ambassador'), ('Tata Sumo', 'Tata Sumo'), ('Maruti Omni', 'Maruti Omni'), ('Maruti Esteem', 'Maruti Esteem'), ('Mahindra Armada', 'Mahindra Armada')], max_length=20)),
                ('ac_type', models.CharField(choices=[('AC', 'AC'), ('Non-AC', 'Non-AC')], max_length=10)),
                ('registration_number', models.CharField(max_length=20, unique=True)),
                ('image', models.ImageField(upload_to='cars/')),
                ('per_hour_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('per_km_charge', models.DecimalField(decimal_places=2, max_digits=6)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fuel_consumption', models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('gas', 'Gas'), ('electric', 'Electric')], default='diesel', max_length=15)),
                ('status', models.CharField(choices=[('available', 'Available'), ('repair', 'Repair')], default='available', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('license_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=7)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=20, unique=True)),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('image', models.ImageField(upload_to='drivers/')),
                ('phone', models.CharField(max_length=15)),
                ('assigned_car', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.car')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_drive', models.BooleanField(default=False)),
                ('start_datetime', models.DateTimeField()),
                ('expected_return_datetime', models.DateTimeField()),
                ('actual_return_datetime', models.DateTimeField(blank=True, null=True)),
                ('advance_payment', models.DecimalField(decimal_places=2, max_digits=8)),
                ('start_km_reading', models.IntegerField()),
                ('end_km_reading', models.IntegerField(blank=True, null=True)),
                ('night_halt', models.BooleanField(default=False)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pickup_location', models.CharField(blank=True, max_length=100, null=True)),
                ('drop_location', models.CharField(blank=True, max_length=100, null=True)),
                ('distance_km', models.FloatField(blank=True, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.driver')),
            ],
        ),
    ]
