# Generated by Django 4.2.23 on 2025-09-09 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='total_cars',
            field=models.IntegerField(default=1),
        ),
    ]
