# Generated by Django 4.2.23 on 2025-10-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_booking_advance_payment_alter_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='kms_to_destination',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
