# Generated by Django 4.2.23 on 2025-10-18 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_booking_kms_to_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='with_driver',
            field=models.BooleanField(default=True),
        ),
    ]
