# Generated by Django 4.2.23 on 2025-11-15 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_driver_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Maintenance',
        ),
    ]
