# Generated by Django 4.2.23 on 2025-11-15 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_maintenance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='damage_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
